@host = http://localhost:5081

###
GET {{host}}/api/products

###
GET {{host}}/api/products/1

###
POST {{host}}/api/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 5.99,
    "stockQuantity": 20
}

###
PUT {{host}}/api/products/1
Content-Type: application/json

{
    "name": "apple-new",
    "price": 7.99,
    "stockQuantity": 15
}

###
POST {{host}}/api/products
Content-Type: application/json

{
    "name": "Invalid",
    "price": -10,
    "stockQuantity": 5
}
