###
GET http://localhost:5081/products

###
GET http://localhost:5081/products/5

###
POST http://localhost:5081/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 5.99,
    "stockQuantity": 20
}

###
PUT http://localhost:5081/products/1
Content-Type: application/json

{
    "name": "apple-new"
}